---
  - name: Install GPG
    sudo: yes
    shell: sudo su - root -c "gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3"

  - name: Install RVM
    sudo: yes
    shell: sudo su - root -c "curl -sSL https://get.rvm.io | bash -s stable --ruby"

  - name: Install ruby
    sudo: yes
    command: sudo su - root -c "rvm install {{ruby_version }}"

  - name: Install ruby gems
    sudo: yes
    shell: sudo su - root -c "cd {{ doc_root }} && bundle install"
